"""Generate the deterministic public fixtures; no source music is read."""
import hashlib,json
from pathlib import Path
import numpy as np
root=Path(__file__).resolve().parents[1]/'examples'
graph=dict(synthetic=True,nodes=list('ABCDEF'),edges=[['A','B',3],['B','C',2],['A','C',-1],
 ['D','E',3],['E','F',2],['D','F',1],['A','D',-3],['B','E',-2],['C','F',-2],['C','D',1]])
rng=np.random.default_rng(20260925)
labels=np.repeat(np.arange(6),8)
centres=rng.normal(size=(6,16))
raw=centres[labels]+rng.normal(scale=.65,size=(48,16))
scaled=(raw-raw.mean(0))/raw.std(0)
vectors=dict(synthetic=True,points=[dict(id=f'SYN-{i+1:02d}',family=f'generated-{labels[i]}',vector=row.tolist()) for i,row in enumerate(scaled)])
for stem,data,kind in [('signed-graph',graph,'synthetic-signed-graph'),('synthetic-vectors',vectors,'synthetic-standardised-vectors')]:
 path=root/f'{stem}.json';path.write_text(json.dumps(data,indent=2)+'\n')
 manifest=dict(schema_version=1,kind=kind,input_sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
               provenance='Artificial teaching fixture generated by tools/make_synthetic.py; not music or an archive sample.')
 (root/f'{stem}.manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
